import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import MyTokenABI from "../abi/MyToken.json";
import {
  useContractRead,
  useAccount,
  usePrepareContractWrite,
  useContractWrite,
  useWaitForTransaction,
} from "wagmi";
import { BigNumber } from "ethers";

const abi = MyTokenABI.abi;
const contractAddress = "0x0493d9E2392390433BAaf0dEc55574A117B1d5C5";

const Home = () => {
  const { address } = useAccount();
  const [mounted, setMounted] = useState(false);

  const { data: balance } = useContractRead<
    typeof abi,
    "balanceOf",
    number | BigNumber | undefined
  >({
    address: contractAddress,
    abi,
    functionName: "balanceOf",
    args: [address],
  });

  const { data: totalSupply } = useContractRead<
    typeof abi,
    "totalSupply",
    number | BigNumber | undefined
  >({
    address: contractAddress,
    abi,
    functionName: "totalSupply",
  });

  const { data: mintPrice } = useContractRead<
    typeof abi,
    "mintPrice",
    number | BigNumber | undefined
  >({
    address: contractAddress,
    abi,
    functionName: "mintPrice",
  });
  const [mintTo, setMintTo] = useState("");

  const { config } = usePrepareContractWrite({
    address: contractAddress,
    abi,
    functionName: "mint",
    args: [mintTo],
    overrides: {
      value: mintPrice,
    },
  });
  const { data, write: mint } = useContractWrite(config);
  const { isError, isLoading, isSuccess } = useWaitForTransaction({
    hash: data?.hash,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>My Token Portal</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h2>My Token</h2>
        <div className={styles.card}>
          <div>Balance</div>
          {balance && <div>{balance.toString()}</div>}
        </div>
        <div className={styles.card}>
          <div>Total Supply</div>
          {totalSupply && <div>{totalSupply.toString()}</div>}
        </div>
        <div className={styles.card}>
          <div>mintPrice</div>
          {mintPrice && <div>{mintPrice.toString()}</div>}
        </div>
        <div className={styles.card}>
          <div>Mint</div>
          <div>
            <input value={mintTo} onChange={(e) => setMintTo(e.target.value)} />
          </div>
          <div>
            <button
              onClick={() => {
                mint?.();
              }}
            >
              Confirm
            </button>
          </div>
          {isSuccess && <div>Mint success</div>}
          {isError && <div>Mint error</div>}
        </div>
      </main>
    </div>
  );
};

export default Home;
